Cocktail.create(name: 'Cuba Libre')
Cocktail.create(name: 'White Russian')
Cocktail.create(name: 'Mojito')
Cocktail.create(name: 'Bloody Mary')
Cocktail.create(name: 'Blue Lagoon')

Ingredient.create(name: 'Whisky')
Ingredient.create(name: 'Rhum')
Ingredient.create(name: 'Lemon')
Ingredient.create(name: 'Ice')
